### ISSUE TITLE
HP-Socket occur 10053 or crash

### ISSUE THREAD

**Issue by skyyearxp** [ldcsaa/HP-Socket#15]
i use hp-socket for tcp server/client develop. at 1000~ clients, always will occur "server 10053 receive onclose event".
how can i debug or know why?
and sometime the exe will crash becasue of the module signature "HPSocket4C_U.dll", how to know the problem?

i download the source code, and build with debug version, got dll/pdb. hope next crash can do something.

我能做些什么来帮助定位10053问题，或者模块崩溃问题么？

**Comment by whatahellworld** [comment]
1.
when 10053 error occurrs,check the status of  your server machine and  application. like mem usage, CPU usage , network usage ,etc... and make sure there is no bugs in your own code.

2.
about crash problem ,  use {SetUnhandledExceptionFilter + MiniDumpWriteDump} to get a crash dump, after crash happened , you can open the dump file with visual studio , and it can help you figure out what caused the crash.(you'd better use debug version , and must have the pdb file. if not , it will be hard to analysis the dump files)

**Comment by ldcsaa** [comment]
1. 10053: you should known that TcpClient is one THREAD per Client, may be thread count were over load, than you should use TcpAgent, which like multi-client that use fixed thread pool.
2. crash: if crash at the time of Stop() method, mostly because that the SocketObj object on processing had been  freeded. you can try to set the property SetFreeSocketObjLockTime() before Start(), default is 10 seconds, set bigger.  Or check your application , where is block.
